### ISSUE TITLE
Sign all the pages in one document

### ISSUE THREAD

**Issue by matheuscarvalho87** [LacunaSoftware/PkiExpressNode#4]
Olá, 

Estou trabalhando com sua API para assinatura digital em documentos, surgiu uma tarefa para nós na qual precisamos mostrar a assinatura em todas as paginas do documento, e não apenas em uma. Já revisamos a documentação de vocês, e entramos em contato com o suporte, eles no indicaram usar o PdfMaker (https://docs.lacunasoftware.com/articles/pki-express/nodejs/visual-rep/index.html), mas isso não resolveria o problema dos nossos clientes. É possível incluir esse recurso na API de vocês?

**Comment by MimyS** [comment]
Olá!

A documentação indicada não é referente ao PdfMarker, mas à representação visual.

**PdfMaker** permite adicionar imagens e textos nos PDFs, desde que antes da realização das assinaturas.
No nosso repositório de exemplos **PkiSuiteSamples** temos exemplos de geração de versão para impressão, em que o PdfMaker é utilizado. (https://github.com/LacunaSoftware/PkiSuiteSamples/blob/master/nodejs/expressmvc/routes/printer-version-pades-express.js#L87)
